### ISSUE TITLE
Cannot import name pdf_read (new)

### ISSUE THREAD

**Issue by jcuna** [chezou/tabula-py#127]
# Summary of your issue
I know many people have opened similar issues, but I've covered all my basis and made sure all of those things were covered. 
I get a `tabula.environment_info() AttributeError: 'module' object has no attribute 'environment_info` same happens with pdf_read. I have made sure I don't have tabula installed and made sure that I had the proper tabula-py package. Happens with both `Python 2.7.10` and `Python 3.6.5`. Moreover, my java installation is fine, in fact, running `java -jar tabula-1.0.2-jar-with-dependencies.jar -p all '/path/to/my/pdf' > file.csv` produces a nice CSV file. Which is the solution I have been working with.

# Environment

Write and check your environment. Please paste outputs of specific commands if required.

- [ ] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: 

```py
# tabula.environment_info() AttributeError: 'module' object has no attribute 'environment_info
```

If not possible to execute `tabula.environment_info()`, please answer following questions manually.

- [ ] Paste the output of `python --version` command on your terminal: 
`python --version
Python 2.7.10`
`python3 --version
Python 3.6.5
`
- [ ] Paste the output of `java -version` command on your terminal: 
~~~~~~~~
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
~~~~~~~~
- [ ] Does `java -h` command work well?; Ensure your java command is included in `PATH`
yes it works fine.
- [ ] Write your OS and it's version: ?
MacOs High Sierra 10.13.6
Providing PDF would be really helpful to resolve the issue.

- [ ] (Optional, but really helpful) Your PDF URL: ?
Like I said, I'm able to create a csv by running `java -jar tabula-1.0.2-jar-with-dependencies.jar -p all '/path/to/my/pdf' > file.csv`

# What did you do when you faced the problem?
Uninstall tabula and tabula-py, then reinstalled again, installed it for python3 as well and tested but issue persisted

Provide your information to reproduce the issue.

## Code:

```
import tabula
from pprint import pprint

pprint(tabula.environment_info())
exit()
```

## Expected behavior:
Some sort of environment info

## Actual behavior:

```
Traceback (most recent call last):
  File "/Users/$MyUserName/Library/Application Support/IntelliJIdea2018.3/python/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/Users/$MyUserName/Library/Application Support/IntelliJIdea2018.3/python/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/$MyUserName/Library/Application Support/IntelliJIdea2018.3/python/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/$MyUserName/Desktop/temp/calendar.py", line 9, in <module>
    import tabula
  File "/Library/Python/2.7/site-packages/tabula/__init__.py", line 1, in <module>
    from .wrapper import read_pdf
  File "/Library/Python/2.7/site-packages/tabula/wrapper.py", line 19, in <module>
    import pandas as pd
  File "/Library/Python/2.7/site-packages/pandas/__init__.py", line 23, in <module>
    from pandas.compat.numpy import *
  File "/Library/Python/2.7/site-packages/pandas/compat/__init__.py", line 423, in <module>
    from dateutil import parser as _date_parser
  File "/Library/Python/2.7/site-packages/dateutil/parser/__init__.py", line 2, in <module>
    from ._parser import parse, parser, parserinfo
  File "/Library/Python/2.7/site-packages/dateutil/parser/_parser.py", line 39, in <module>
    from calendar import monthrange
  File "/Users/$MyUserName/Desktop/temp/calendar.py", line 20, in <module>
    tabula.environment_info()
AttributeError: 'module' object has no attribute 'environment_info'
```
![screen shot 2019-01-10 at 7 23 30 pm](https://user-images.githubusercontent.com/5770133/51006461-4f441500-1511-11e9-8f16-d860e8b10897.png)
![screen shot 2019-01-10 at 7 25 04 pm](https://user-images.githubusercontent.com/5770133/51006463-50754200-1511-11e9-9226-f321fba17d9c.png)
[Screen Shot 2019-01-10 at 7.23.30 PM.pdf](https://github.com/chezou/tabula-py/files/2747616/Screen.Shot.2019-01-10.at.7.23.30.PM.pdf)

**Comment by chezou** [comment]
@jcuna Thank you for reporting. Could you try following commands?

```sh
$ pip --version
```

```python
import tabula
print(tabula)
```

**Comment by chezou** [comment]
BTW, don't you try to `import calendar` from `calendar.py`? 
Python has a standard library called `calendar.py` https://docs.python.org/2/library/calendar.html and you might conflict with the standard library.

How about renaming your `calendar.py` to another file name? and how about importing from REPL?

**Comment by jcuna** [comment]
@chezou thanks.
~~~~~~~~~~~
pip --version
pip 18.1 from /Library/Python/2.7/site-packages/pip (python 2.7)
pip3 --version
pip 18.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
~~~~~~~~~~~

The output of print tabula
~~~~~~~~~~~~~~~~~~~
<module 'tabula' from '/Library/Python/2.7/site-packages/tabula/__init__.pyc'>
~~~~~~~~~~~~~~~~~~~

**Comment by jcuna** [comment]
I do not `import calendar` from `calendar`. I'll try renaming the file though
