### ISSUE TITLE
subprocess.CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar'

### ISSUE THREAD

**Issue by mohan2515175** [chezou/tabula-py#137]
# Summary of your issue
Code:

import tabula

dflist = tabula.read_pdf("NSE100011130-JAN-19PS04.pdf", encoding='utf-8', spreadsheet=True, multiple_tables=True)

with open('NSE100011130-JAN-19PS04.pdf.csv', 'a') as f:
    for i, df in enumerate(dflist):
        dflist[i].to_csv(f, header=False)

    

Error: 
Traceback (most recent call last):
  File "C:\Users\mohan\AppData\Local\Programs\Python\Python36-32\pdftocsv.py", line 10, in <module>
    dflist = tabula.read_pdf(one_pdf, encoding='utf-8', spreadsheet=True,multiple_tables=True)
  File "C:\Users\mohan\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tabula\wrapper.py", line 108, in read_pdf
    output = subprocess.check_output(args)
  File "C:\Users\mohan\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "C:\Users\mohan\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\\Users\\mohan\\AppData\\Local\\Programs\\Python\\Python36-32\\lib\\site-packages\\tabula\\tabula-1.0.2-jar-with-dependencies.jar', '--pages', '1', '--guess', '--format', 'JSON', '--lattice', 'C:\\Users\\mohan\\AppData\\Local\\Programs\\Python\\Python36-32\\NSE100011108-FEB-19PS04.pdf']' returned non-zero exit status 1.

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
