### ISSUE TITLE
output_format="json" returns dataframe

### ISSUE THREAD

**Issue by javiermarcon** [chezou/tabula-py#176]
I run read_pdf with output_format="json" and the output is a dataframe instead of a json string

jt = tabula.read_pdf('/home/javier/info_cc.pdf', output_format="json", pages=8,
                  multiple_tables=True, stream=True, guess=False)
sep. 29, 2019 10:48:11 A. M. org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
ADVERTENCIA: New fonts found, font cache will be re-built
sep. 29, 2019 10:48:11 A. M. org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
ADVERTENCIA: Building on-disk font cache, this may take a while
sep. 29, 2019 10:48:13 A. M. org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
ADVERTENCIA: Finished building on-disk font cache, found 766 fonts
type(jt[0])
<class 'pandas.core.frame.DataFrame'>
tabula.environment_info()
Python version:
    3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
Java version:
    openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
tabula-py version: 1.4.1
platform: Linux-4.15.0-64-generic-x86_64-with-Ubuntu-18.04-bionic
uname:
    uname_result(system='Linux', node='javier-System-Product-Name', release='4.15.0-64-generic', version='#73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019', machine='x86_64', processor='x86_64')
linux_distribution: ('Ubuntu', '18.04', 'bionic')
mac_ver: ('', ('', '', ''), '')

How can I get the jsond output (with the esxtra information that it has) to read the tables of the document?

jt = tabula.read_pdf('/home/javier/info_cc.pdf', output_format="json", pages='all',
                  multiple_tables=True, stream=True, guess=False)
sep. 29, 2019 10:51:25 A. M. org.apache.pdfbox.filter.FlateFilter decode
GRAVE: FlateFilter: stop reading corrupt stream due to a DataFormatException
sep. 29, 2019 10:51:25 A. M. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
ADVERTENCIA: Could not read embedded TTF for font AACHAM+Wingdings
java.io.IOException: java.util.zip.DataFormatException: invalid literal/lengths set
	at org.apache.pdfbox.filter.FlateFilter.decode(FlateFilter.java:58)
	at org.apache.pdfbox.filter.Filter.decode(Filter.java:87)
	at org.apache.pdfbox.cos.COSInputStream.create(COSInputStream.java:77)
	at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:175)
	at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:163)
	at org.apache.pdfbox.pdmodel.common.PDStream.createInputStream(PDStream.java:236)
	at org.apache.pdfbox.pdmodel.font.PDTrueTypeFont.<init>(PDTrueTypeFont.java:198)
	at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:75)
	at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:146)
	at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:60)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:869)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:505)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:479)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:152)
	at technology.tabula.ObjectExtractor.extractPage(ObjectExtractor.java:26)
	at technology.tabula.PageIterator.next(PageIterator.java:29)
	at technology.tabula.CommandLineApp.extractFile(CommandLineApp.java:165)
	at technology.tabula.CommandLineApp.extractFileTables(CommandLineApp.java:128)
	at technology.tabula.CommandLineApp.extractTables(CommandLineApp.java:109)
	at technology.tabula.CommandLineApp.main(CommandLineApp.java:79)
Caused by: java.util.zip.DataFormatException: invalid literal/lengths set
	at java.base/java.util.zip.Inflater.inflateBytesBytes(Native Method)
	at java.base/java.util.zip.Inflater.inflate(Inflater.java:385)
	at java.base/java.util.zip.Inflater.inflate(Inflater.java:471)
	at org.apache.pdfbox.filter.FlateFilter.decompress(FlateFilter.java:83)
	at org.apache.pdfbox.filter.FlateFilter.decode(FlateFilter.java:50)
	... 19 more
sep. 29, 2019 10:51:25 A. M. org.apache.pdfbox.pdmodel.font.PDTrueTypeFont <init>
ADVERTENCIA: Using fallback font 'ArialMT' for 'AACHAM+Wingdings'
[info_cc.pdf](https://github.com/chezou/tabula-py/files/3667411/info_cc.pdf)
[info_cc.pdf](https://github.com/chezou/tabula-py/files/3667412/info_cc.pdf)

**Comment by chezou** [comment]
This report is not following the template, so closing the issue. Please file the bug with the information described in the template so that I understand the situation clearly. Thanks.
