### ISSUE TITLE
Won't read pdf when filename contains scandinavian letter å

### ISSUE THREAD

**Issue by Schmoobenstein** [chezou/tabula-py#266]
# Summary of your issue

I tried to read the tables from the file 'Delårsrapport-Eolus-Vind-2020-02-29-Uppdaterad.pdf' (downloaded from https://www.eolusvind.com/wp-content/uploads/2020/05/Dela%CC%8Arsrapport-Eolus-Vind-2020-02-29-Uppdaterad.pdf). Using the following code in Spyder (v.4.1.5)

`import tabula 
 filename = 'Delårsrapport-Eolus-Vind-2020-02-29-Uppdaterad.pdf'
 tables = tabula.read_pdf(filename)`
    

This gave me the following output
Error: 

Traceback (most recent call last):

  File "C:\repos\Coursera\financial_engineering_1\untitled0.py", line 11, in <module>
    tables = tabula.read_pdf(filename)

  File "C:\Users\morte\Anaconda3\lib\site-packages\tabula\wrapper.py", line 147, in read_pdf
    output = _run(java_options, kwargs, path, encoding)

  File "C:\Users\morte\Anaconda3\lib\site-packages\tabula\wrapper.py", line 67, in _run
    return subprocess.check_output(args)

  File "C:\Users\morte\Anaconda3\lib\subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "C:\Users\morte\Anaconda3\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\\Users\\morte\\Anaconda3\\lib\\site-packages\\tabula\\tabula-1.0.3-jar-with-dependencies.jar', '--pages', '1', '--guess', 'Delårsrapport-Eolus-Vind-2020-02-29-Uppdaterad.pdf']' returned non-zero exit status 1.

Error: File does not exist

However, after changing the filename, substituting the 'å' with an 'a' it works.

# Check list before submit

- [x] Did you read [FAQ](https://tabula-py.readthedocs.io/en/latest/faq.html)?

- [x] (Optional, but really helpful) Your PDF URL: https://www.eolusvind.com/wp-content/uploads/2020/05/Dela%CC%8Arsrapport-Eolus-Vind-2020-02-29-Uppdaterad.pdf

- [x] Paste the output of `import tabula; tabula.environment_info()` on Python REPL: ?
tabula.environment_info()
Python version:
    3.7.7 (default, Mar 23 2020, 23:19:08) [MSC v.1916 64 bit (AMD64)]
Java version:
    openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Zulu11.41+23-CA (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.41+23-CA (build 11.0.8+10-LTS, mixed mode)
tabula-py version: 1.4.1
platform: Windows-10-10.0.18362-SP0
uname:
    uname_result(system='Windows', node='DESKTOP-R1U744N', release='10', version='10.0.18362', machine='AMD64', processor='Intel64 Family 6 Model 142 Stepping 9, GenuineIntel')
linux_distribution: ('', '', '')
mac_ver: ('', ('', '', ''), '')
- [x] Paste the output of `python --version` command on your terminal: 3.7.7
- [x] Paste the output of `java -version` command on your terminal: 
       openjdk version "11.0.8" 2020-07-14 LTS
       OpenJDK Runtime Environment Zulu11.41+23-CA (build 11.0.8+10-LTS)
       OpenJDK 64-Bit Server VM Zulu11.41+23-CA (build 11.0.8+10-LTS, mixed mode)
- [x] Does `java -h` command work well?; Ensure your java command is included in `PATH`: yes
- [x] Write your OS and it's version: Windows 10
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18362  0       

# What did you do when you faced the problem?
Changed the filename, substituting the 'å' with an 'a' 

## Code:

import tabula
filename = 'Delarsrapport-Eolus-Vind-2020-02-29-Uppdaterad.pdf'
tables = tabula.read_pdf(filename)

## Expected behavior:

```
write your expected output
```

## Actual behavior:

Then it worked as expected

**Comment by chezou** [comment]
Can't reproduce on my Mac. Looks like you're using outdated version 1.4.1. Can you try latest tabula-py v2.2.0?

```
In [1]: fname = "Delårsrapport-Eolus-Vind-2020-02-29-Uppdaterad.pdf"

In [2]: import tabula

In [3]: dfs = tabula.read_pdf(fname)
'pages' argument isn't specified.Will extract only from page 1 by default.

In [4]: dfs
Out[4]:
[                     Koncernens resultat i korthet                De lå r             De lå r.1         Ac kumule ra t      Ac kumule ra t.1               He lå r
 0                                              NaN      2 0 19 - 12 - 0 1     2 0 18 - 12 - 0 1     2 0 19 - 0 9 - 0 1    2 0 18 - 0 9 - 0 1    2 0 18 - 0 9 - 0 1
 1                                              NaN  - 2 0 2 0 - 0 2 - 2 9  - 2 0 19 - 0 2 - 2 8  - 2 0 2 0 - 0 2 - 2 9  - 2 0 19 - 0 2 - 2 8  - 2 0 19 - 0 8 - 3 1
 2                            Nettoomsättning, MSEK                  259,4                 370,2                  553,7                 477,9               2 031,9
 3                            Rörelseresultat, MSEK                   53,0                  25,9                  105,3                  35,5                 118,3
 4                        Resultat före skatt, MSEK                   57,7                  31,2                   95,2                  33,3                 116,0
 5      Värdeförändringar derivat före skatt, MSEK*                   -6,1                 -24,8                   20,0                 -21,2                 -24,9
 6                         Periodens resultat, MSEK                   75,7                  38,7                  117,8                  39,7                 132,8
 7   Resultat per aktie före/efter utspädning, SEK*                   3,04                  1,55                   4,73                  1,59                  5,33
 8                     Eget kapital per aktie, SEK*                  38,78                 31,96                  38,78                 31,96                 35,65
 9   Kassaflöde från den löpande verksamheten, MSEK                 -148,4                 277,5                 -400,0                 -25,7                 566,6
 10                          Balansomslutning, MSEK                1 868,6               1 708,5                1 868,6               1 708,5               2 057,8
 11               Nettoskuld - /nettokassa +, MSEK*                  355,1                 209,6                  355,1                 209,6                 800,1
 12                Orderstock per balansdagen, MSEK                5 116,6               3 116,8                5 116,6               3 116,8               1 348,9
 13           Under perioden drifttagna verk, antal                      -                   3,0                   43,0                   3,0                  31,0
 14               Verk överlämnade till kund, antal                    1,0                   3,0                   44,0                   4,0                  34,0
 15              Under perioden drifttagna verk, MW                      -                  10,8                  163,4                  10,8                 115,2
 16                  Verk överlämnade till kund, MW                    0,8                  10,8                  164,2                  12,8                 120,0
 17                             Förvaltade verk, MW                    687                   421                    687                   421                   524
 18                                   Soliditet, %*                   51,6                  46,7                   51,6                  46,7                  43,2
 19      Avkastning på eget kapital efter skatt, %*                   23,9                  26,1                   23,9                  26,1                  15,6]
```

**Comment by chezou** [comment]
I double-checked and I found you need to call `chcp 65001` on your terminal before launching Python process.

```sh
λ  chcp 65001
Active code page: 65001
C:\Users\chezo\source\tabula-py [master ≡ +2 ~0 -0 !]
λ  .\.venv\Scripts\ipython.exe
```
```py
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import tabula

IIn [2]: fname = "Delårsrapport-Eolus-Vind-2020-02-29-Uppdaterad.pdf"

In [4]: dfs = tabula.read_pdf(fname)
'pages' argument isn't specified.Will extract only from page 1 by default.
Got stderr: 9 30, 2020 9:43:03 午前 org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
警告: New fonts found, font cache will be re-built
9 30, 2020 9:43:03 午前 org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
警告: Building on-disk font cache, this may take a while
9 30, 2020 9:43:11 午前 org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
警告: Finished building on-disk font cache, found 542 fonts


In [5]: dfs
Out[5]:
[                     Koncernens resultat i korthet                De lå r          ...               Ac kumule ra t.1               He lå r

 0                                              NaN      2 0 19 - 12 - 0 1          ...             2 0 18 - 0 9 - 0 1    2 0 18 - 0 9 - 0 1

 1                                              NaN  - 2 0 2 0 - 0 2 - 2 9          ...           - 2 0 19 - 0 2 - 2 8  - 2 0 19 - 0 8 - 3 1

 2                            Nettoomsättning, MSEK                  259,4          ...                          477,9               2 031,9

 3                            Rörelseresultat, MSEK                   53,0          ...                           35,5                 118,3

 4                        Resultat före skatt, MSEK                   57,7          ...                           33,3                 116,0

 5      Värdeförändringar derivat före skatt, MSEK*                   -6,1          ...                          -21,2                 -24,9

 6                         Periodens resultat, MSEK                   75,7          ...                           39,7                 132,8

 7   Resultat per aktie före/efter utspädning, SEK*                   3,04          ...                           1,59                  5,33

 8                     Eget kapital per aktie, SEK*                  38,78          ...                          31,96                 35,65

 9   Kassaflöde från den löpande verksamheten, MSEK                 -148,4          ...                          -25,7                 566,6

 10                          Balansomslutning, MSEK                1 868,6          ...                        1 708,5               2 057,8

 11               Nettoskuld - /nettokassa +, MSEK*                  355,1          ...                          209,6                 800,1

 12                Orderstock per balansdagen, MSEK                5 116,6          ...                        3 116,8               1 348,9

 13           Under perioden drifttagna verk, antal                      -          ...                            3,0                  31,0

 14               Verk överlämnade till kund, antal                    1,0          ...                            4,0                  34,0

 15              Under perioden drifttagna verk, MW                      -          ...                           10,8                 115,2

 16                  Verk överlämnade till kund, MW                    0,8          ...                           12,8                 120,0

 17                             Förvaltade verk, MW                    687          ...                            421                   524

 18                                   Soliditet, %*                   51,6          ...                           46,7                  43,2

 19      Avkastning på eget kapital efter skatt, %*                   23,9          ...                           26,1                  15,6


 [20 rows x 6 columns]]
```
